### PR TITLE
add cuDNN v5 support, drop cuDNN v3 support

### PR DESCRIPTION
**Pull request by ningzhou**
The change was purely based on BVLC/caffe#4159

### CODE REVIEW

**Review by Cysu — CHANGES_REQUESTED** [review]
Could you please consider switch back to the original lib64 path? As other linux distributions (ubuntu 14.04, arch linux) do not have lib/x86_64-linux-gpu under cuda.

**Review by Cysu — APPROVED** [review]

**Comment by Cysu** [comment]
@ningzhou I have merged the PR. Thank you very much!

**Comment by ningzhou** [comment]
You are very welcome. In fact, thank you very much for open sourcing the
excellent work.

Ning

**Comment by ningzhou** [comment]
sure. I will create a new pull request.

**Pull request merged**
